//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Check_Circle {
            get {
                object obj = ResourceManager.GetObject("Check_Circle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;skilteproduktion_view&quot;,&quot;skilteproduktion&quot;,&quot;Skilteproduktion - Tekstil - XFAMILY&quot;,&quot;configurable&quot;,&quot;1195,XCAT&quot;,&quot;XSKU&quot;,&quot;0&quot;,&quot;XNAME&quot;,&quot;XNAME&quot;,&quot;XSKU&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;XSKU&quot;,&quot;XSKU.html&quot;,&quot;&quot;,&quot;No layout updates&quot;,&quot;Product Info Column&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot; &quot;,&quot;No&quot;,&quot;In Cart&quot;,&quot;No&quot;,&quot;&quot;,&quot;&quot;,&quot;XPRICE.0000&quot;,&quot;&quot;,&quot;0.0000&quot;,&quot;Enabled&quot;,&quot;1&quot;,&quot;No&quot;,&quot;Momspligtige varer 25 %&quot;,&quot;XFAMILY&quot;,&quot;&quot;,&quot;&quot;,&quot;XDESC&quot;,&quot;XDESC&quot;,&quot;XSKU&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;0.0000&quot;,&quot;0.0000&quot;,&quot;1&quot;,&quot;0&quot;,&quot;0&quot;,&quot;1&quot;,&quot;1.0000&quot;,&quot;1&quot;,&quot;0.0000&quot;,&quot;1&quot;,&quot....
        /// </summary>
        internal static string configurable {
            get {
                return ResourceManager.GetString("configurable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cross_Cricle {
            get {
                object obj = ResourceManager.GetObject("Cross_Cricle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;store&quot;,&quot;websites&quot;,&quot;attribute_set&quot;,&quot;type&quot;,&quot;category_ids&quot;,&quot;sku&quot;,&quot;has_options&quot;,&quot;name&quot;,&quot;meta_title&quot;,&quot;meta_description&quot;,&quot;image&quot;,&quot;small_image&quot;,&quot;thumbnail&quot;,&quot;url_key&quot;,&quot;url_path&quot;,&quot;custom_design&quot;,&quot;page_layout&quot;,&quot;options_container&quot;,&quot;image_label&quot;,&quot;small_image_label&quot;,&quot;thumbnail_label&quot;,&quot;country_of_manufacture&quot;,&quot;msrp_enabled&quot;,&quot;msrp_display_actual_price_type&quot;,&quot;gift_message_available&quot;,&quot;supplier_sku&quot;,&quot;supplier_name&quot;,&quot;price&quot;,&quot;special_price&quot;,&quot;msrp&quot;,&quot;status&quot;,&quot;visibility&quot;,&quot;enable_googlecheckout&quot;,&quot;tax_class_id&quot;,&quot;txt_family&quot;,&quot;txt_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string csv {
            get {
                return ResourceManager.GetString("csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Csv1 {
            get {
                object obj = ResourceManager.GetObject("Csv1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kirneh {
            get {
                object obj = ResourceManager.GetObject("kirneh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;store&quot;,&quot;websites&quot;,&quot;attribute_set&quot;,&quot;type&quot;,&quot;category_ids&quot;,&quot;sku&quot;,&quot;has_options&quot;,&quot;name&quot;,&quot;meta_title&quot;,&quot;meta_description&quot;,&quot;image&quot;,&quot;small_image&quot;,&quot;thumbnail&quot;,&quot;url_key&quot;,&quot;url_path&quot;,&quot;custom_design&quot;,&quot;page_layout&quot;,&quot;options_container&quot;,&quot;image_label&quot;,&quot;small_image_label&quot;,&quot;thumbnail_label&quot;,&quot;country_of_manufacture&quot;,&quot;msrp_enabled&quot;,&quot;msrp_display_actual_price_type&quot;,&quot;gift_message_available&quot;,&quot;supplier_sku&quot;,&quot;supplier_name&quot;,&quot;price&quot;,&quot;special_price&quot;,&quot;msrp&quot;,&quot;status&quot;,&quot;visibility&quot;,&quot;enable_googlecheckout&quot;,&quot;tax_class_id&quot;,&quot;txt_family&quot;,&quot;txt_ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string poloer {
            get {
                return ResourceManager.GetString("poloer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;skilteproduktion_view&quot;,&quot;skilteproduktion&quot;,&quot;Skilteproduktion - Tekstil - XFAMILY&quot;,&quot;simple&quot;,&quot;&quot;,&quot;XSKU&quot;,&quot;0&quot;,&quot;XNAME XCOLOR XSIZE&quot;,&quot;XNAME&quot;,&quot;XSKU&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;XSKU&quot;,&quot;XSKU.html&quot;,&quot;&quot;,&quot;No layout updates&quot;,&quot;Product Info Column&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot; &quot;,&quot;No&quot;,&quot;In Cart&quot;,&quot;No&quot;,&quot;&quot;,&quot;&quot;,&quot;25.0000&quot;,&quot;&quot;,&quot;&quot;,&quot;Enabled&quot;,&quot;4&quot;,&quot;No&quot;,&quot;Momspligtige varer 25 %&quot;,&quot;XFAMILY&quot;,&quot;XSIZE&quot;,&quot;XCOLOR&quot;,&quot;XNAME XCOLOR XSIZE&quot;,&quot;XNAME XCOLOR XSIZE&quot;,&quot;XSKU&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;&quot;,&quot;0.0000&quot;,&quot;0.0000&quot;,&quot;1&quot;,&quot;0&quot;,&quot;0&quot;,&quot;1&quot;,&quot;1.0000&quot;,&quot;1&quot;,&quot;0.0000&....
        /// </summary>
        internal static string simple {
            get {
                return ResourceManager.GetString("simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap triangle_down {
            get {
                object obj = ResourceManager.GetObject("triangle_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap triangle_up {
            get {
                object obj = ResourceManager.GetObject("triangle_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
